//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Kursovoi_proekt
{
    using System;
    using System.Collections.Generic;
    
    public partial class Korzina
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Korzina()
        {
            this.Zakaz = new HashSet<Zakaz>();
        }
    
        public int id { get; set; }
        public Nullable<int> idKlient { get; set; }
        public Nullable<int> idNiutbook { get; set; }
        public Nullable<int> IsZakaz { get; set; }
    
        public virtual Client Client { get; set; }
        public virtual Noutbook Noutbook { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Zakaz> Zakaz { get; set; }
    }
}
