//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Kursovoi_proekt
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class KursovikBDEntities : DbContext
    {
        public KursovikBDEntities()
            : base("name=KursovikBDEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Client> Client { get; set; }
        public virtual DbSet<Disk> Disk { get; set; }
        public virtual DbSet<Firm> Firm { get; set; }
        public virtual DbSet<Korzina> Korzina { get; set; }
        public virtual DbSet<Noutbook> Noutbook { get; set; }
        public virtual DbSet<Processor> Processor { get; set; }
        public virtual DbSet<StatusZakaz> StatusZakaz { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<TypeMemory> TypeMemory { get; set; }
        public virtual DbSet<Videokarta> Videokarta { get; set; }
        public virtual DbSet<Zakaz> Zakaz { get; set; }
    }
}
