//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Kursovoi_proekt
{
    using System;
    using System.Collections.Generic;
    
    public partial class Noutbook
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Noutbook()
        {
            this.Korzina = new HashSet<Korzina>();
        }
    
        public int id { get; set; }
        public string Name { get; set; }
        public Nullable<double> Price { get; set; }
        public Nullable<int> Processor { get; set; }
        public Nullable<double> OZUGB { get; set; }
        public Nullable<int> DisckType { get; set; }
        public Nullable<double> DiskValueMemoryGB { get; set; }
        public Nullable<int> Videokarta { get; set; }
        public string Color { get; set; }
        public Nullable<double> Diagonal { get; set; }
        public Nullable<int> Firm { get; set; }
        public Nullable<int> Value { get; set; }
    
        public virtual Disk Disk { get; set; }
        public virtual Firm Firm1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Korzina> Korzina { get; set; }
        public virtual Processor Processor1 { get; set; }
        public virtual Videokarta Videokarta1 { get; set; }
    }
}
