//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Kursovoi_proekt
{
    using System;
    using System.Collections.Generic;
    
    public partial class Zakaz
    {
        public int id { get; set; }
        public Nullable<int> idKorzina { get; set; }
        public string Adres { get; set; }
        public Nullable<int> StatusZakaz { get; set; }
    
        public virtual Korzina Korzina { get; set; }
        public virtual StatusZakaz StatusZakaz1 { get; set; }
    }
}
